name = input("Enter your name:")
age = input("Enter your age:")
aadhaar = input("Enter your Aadhar number:")
pan = input("Enter your PAN number:")
email = input("Enter your email address:")
father_name = input("Enter your father name:")
mother_name = input("Enter your mother name:")
phone = input("Enter your phone number:")

print("\n----- User Details -----")
print("Name:", name)
print("Age:", age)
print("Aadhaar:", aadhaar)
print("PAN:", pan)
print("Email:", email)
print("Father Name:", father_name)
print("Mother Name:", mother_name)
print("Phone:", phone)